name: "mihcall blog"
author: Michał Śliwoń
fullname: Michał Śliwoń
markdown: rdiscount
highlighter: "pygments"
encoding: "utf-8"
permalink: /:year/:month/:day/:title/

rdiscount:
  extensions: [smart]

url: http://blog.mihcall.com
description: My blog
twitter: mihcall
github: mihcall
gravatar_url: http://www.gravatar.com/avatar/4fb1ca49c9dca9afe96bec2be2a28aa9
